export default [
  { name: 'Afghanistan', cnName: '阿富汗', countryCode: 'AF', telSortCode: 93 },
  { name: 'Albania', cnName: '阿尔巴尼亚', countryCode: 'AL', telSortCode: 355 },
  { name: 'Algeria', cnName: '阿尔及利亚', countryCode: 'DZ', telSortCode: 213 },
  { name: 'American Samoa', cnName: '美属萨摩亚', countryCode: 'AS', telSortCode: 1 },
  { name: 'Andorra', cnName: '安道尔', countryCode: 'AD', telSortCode: 376 },
  { name: 'Angola', cnName: '安哥拉', countryCode: 'AO', telSortCode: 244 },
  { name: 'Anguilla', cnName: '安圭拉', countryCode: 'AI', telSortCode: 1 },
  { name: 'Antarctica', cnName: '南极洲', countryCode: 'AQ', telSortCode: 672 },
  { name: 'Antigua and Barbuda', cnName: '安提瓜和巴布达', countryCode: 'AG', telSortCode: 1 },
  { name: 'Argentina', cnName: '阿根廷', countryCode: 'AR', telSortCode: 54 },
  { name: 'Armenia', cnName: '亚美尼亚', countryCode: 'AM', telSortCode: 374 },
  { name: 'Aruba', cnName: '阿鲁巴', countryCode: 'AW', telSortCode: 297 },
  { name: 'Australia', cnName: '澳大利亚', countryCode: 'AU', telSortCode: 61 },
  { name: 'Austria', cnName: '奥地利', countryCode: 'AT', telSortCode: 43 },
  { name: 'Azerbaijan', cnName: '阿塞拜疆', countryCode: 'AZ', telSortCode: 994 },
  { name: 'Bahamas', cnName: '巴哈马', countryCode: 'BS', telSortCode: 1 },
  { name: 'Bahrain', cnName: '巴林', countryCode: 'BH', telSortCode: 973 },
  { name: 'Bangladesh', cnName: '孟加拉国', countryCode: 'BD', telSortCode: 880 },
  { name: 'Barbados', cnName: '巴巴多斯', countryCode: 'BB', telSortCode: 1 },
  { name: 'Belarus', cnName: '白俄罗斯', countryCode: 'BY', telSortCode: 375 },
  { name: 'Belgium', cnName: '比利时', countryCode: 'BE', telSortCode: 32 },
  { name: 'Belize', cnName: '伯利兹', countryCode: 'BZ', telSortCode: 501 },
  { name: 'Benin', cnName: '贝宁', countryCode: 'BJ', telSortCode: 229 },
  { name: 'Bermuda', cnName: '百慕大', countryCode: 'BM', telSortCode: 1 },
  { name: 'Bhutan', cnName: '不丹', countryCode: 'BT', telSortCode: 975 },
  { name: 'Bolivia', cnName: '玻利维亚', countryCode: 'BO', telSortCode: 591 },
  { name: 'Bosnia and Herzegovina', cnName: '波斯尼亚和黑塞哥维那', countryCode: 'BA', telSortCode: 387 },
  { name: 'Botswana', cnName: '博茨瓦纳', countryCode: 'BW', telSortCode: 267 },
  { name: 'Brazil', cnName: '巴西', countryCode: 'BR', telSortCode: 55 },
  { name: 'British Indian Ocean Territory', cnName: '英属印度洋领地', countryCode: 'IO', telSortCode: 246 },
  { name: 'British Virgin Islands', cnName: '英属维尔京群岛', countryCode: 'VG', telSortCode: 1 },
  { name: 'Brunei', cnName: '文莱', countryCode: 'BN', telSortCode: 673 },
  { name: 'Bulgaria', cnName: '保加利亚', countryCode: 'BG', telSortCode: 359 },
  { name: 'Burkina Faso', cnName: '布基纳法索', countryCode: 'BF', telSortCode: 226 },
  { name: 'Burundi', cnName: '布隆迪', countryCode: 'BI', telSortCode: 257 },
  { name: 'Cambodia', cnName: '柬埔寨', countryCode: 'KH', telSortCode: 855 },
  { name: 'Cameroon', cnName: '喀麦隆', countryCode: 'CM', telSortCode: 237 },
  { name: 'Canada', cnName: '加拿大', countryCode: 'CA', telSortCode: 1 },
  { name: 'Cape Verde', cnName: '佛得角', countryCode: 'CV', telSortCode: 238 },
  { name: 'Cayman Islands', cnName: '开曼群岛', countryCode: 'KY', telSortCode: 1 },
  { name: 'Central African Republic', cnName: '中非共和国', countryCode: 'CF', telSortCode: 236 },
  { name: 'Chad', cnName: '乍得', countryCode: 'TD', telSortCode: 235 },
  { name: 'Chile', cnName: '智利', countryCode: 'CL', telSortCode: 56 },
  { name: 'China', cnName: '中国', countryCode: 'CN', telSortCode: 86 },
  { name: 'Christmas Islands', cnName: '圣诞岛', countryCode: 'CX', telSortCode: 61 },
  { name: 'Cocos Islands', cnName: '科科斯群岛', countryCode: 'CC', telSortCode: 61 },
  { name: 'Colombia', cnName: '哥伦比亚', countryCode: 'CO', telSortCode: 57 },
  { name: 'Comoros', cnName: '科摩罗', countryCode: 'KM', telSortCode: 269 },
  { name: 'Cook Islands', cnName: '库克群岛', countryCode: 'CK', telSortCode: 682 },
  { name: 'Costa Rica', cnName: '哥斯达黎加', countryCode: 'CR', telSortCode: 506 },
  { name: 'Croatia', cnName: '克罗地亚', countryCode: 'HR', telSortCode: 385 },
  { name: 'Cuba', cnName: '古巴', countryCode: 'CU', telSortCode: 53 },
  { name: 'Curacao', cnName: '库拉索', countryCode: 'CW', telSortCode: 599 },
  { name: 'Cyprus', cnName: '塞浦路斯', countryCode: 'CY', telSortCode: 357 },
  { name: 'Czech Republic', cnName: '捷克共和国', countryCode: 'CZ', telSortCode: 420 },
  { name: 'Democratic Republic of the Congo', cnName: '刚果民主共和国', countryCode: 'CD', telSortCode: 243 },
  { name: 'Denmark', cnName: '丹麦', countryCode: 'DK', telSortCode: 45 },
  { name: 'Djibouti', cnName: '吉布提', countryCode: 'DJ', telSortCode: 253 },
  { name: 'Dominica', cnName: '多米尼加', countryCode: 'DM', telSortCode: 1 },
  { name: 'Dominican Republic', cnName: '多明尼加共和国', countryCode: 'DO', telSortCode: 1 },
  { name: 'East Timor', cnName: '东帝汶', countryCode: 'TL', telSortCode: 670 },
  { name: 'Ecuador', cnName: '厄瓜多尔', countryCode: 'EC', telSortCode: 593 },
  { name: 'Egypt', cnName: '埃及', countryCode: 'EG', telSortCode: 20 },
  { name: 'El Salvador', cnName: '萨尔瓦多', countryCode: 'SV', telSortCode: 503 },
  { name: 'Equatorial Guinea', cnName: '赤道几内亚', countryCode: 'GQ', telSortCode: 240 },
  { name: 'Eritrea', cnName: '厄立特里亚', countryCode: 'ER', telSortCode: 291 },
  { name: 'Estonia', cnName: '爱沙尼亚', countryCode: 'EE', telSortCode: 372 },
  { name: 'Ethiopia', cnName: '埃塞俄比亚', countryCode: 'ET', telSortCode: 251 },
  { name: 'Falkland Islands', cnName: '福克兰群岛', countryCode: 'FK', telSortCode: 500 },
  { name: 'Faroe Islands', cnName: '法罗群岛', countryCode: 'FO', telSortCode: 298 },
  { name: 'Fiji', cnName: '斐济', countryCode: 'FJ', telSortCode: 679 },
  { name: 'Finland', cnName: '芬兰', countryCode: 'FI', telSortCode: 358 },
  { name: 'France', cnName: '法国', countryCode: 'FR', telSortCode: 33 },
  { name: 'French Polynesia', cnName: '法属波利尼西亚', countryCode: 'PF', telSortCode: 689 },
  { name: 'Gabon', cnName: '加蓬', countryCode: 'GA', telSortCode: 241 },
  { name: 'Gambia', cnName: '冈比亚', countryCode: 'GM', telSortCode: 220 },
  { name: 'Georgia', cnName: '格鲁吉亚', countryCode: 'GE', telSortCode: 995 },
  { name: 'Germany', cnName: '德国', countryCode: 'DE', telSortCode: 49 },
  { name: 'Ghana', cnName: '加纳', countryCode: 'GH', telSortCode: 233 },
  { name: 'Gibraltar', cnName: '直布罗陀', countryCode: 'GI', telSortCode: 350 },
  { name: 'Greece', cnName: '希腊', countryCode: 'GR', telSortCode: 30 },
  // { name: 'Greenland', cnName: '格陵兰', countryCode: 'GL', telSortCode: 299 },
  { name: 'Global', cnName: '全球', countryCode: 'GL', telSortCode: 299 },
  { name: 'Grenada', cnName: '格林纳达', countryCode: 'GD', telSortCode: 1 },
  { name: 'Guam', cnName: '关岛', countryCode: 'GU', telSortCode: 1 },
  { name: 'Guatemala', cnName: '危地马拉', countryCode: 'GT', telSortCode: 502 },
  { name: 'Guernsey', cnName: '根西岛', countryCode: 'GG', telSortCode: 44 },
  { name: 'Guinea', cnName: '几内亚', countryCode: 'GN', telSortCode: 224 },
  { name: 'Guinea-Bissau', cnName: '几内亚比绍', countryCode: 'GW', telSortCode: 245 },
  { name: 'Guyana', cnName: '圭亚那', countryCode: 'GY', telSortCode: 592 },
  { name: 'Haiti', cnName: '海地', countryCode: 'HT', telSortCode: 509 },
  { name: 'Honduras', cnName: '洪都拉斯', countryCode: 'HN', telSortCode: 504 },
  { name: 'Hong Kong', cnName: '香港特别行政区', countryCode: 'HK', telSortCode: 852 },
  { name: 'Hungary', cnName: '匈牙利', countryCode: 'HU', telSortCode: 36 },
  { name: 'Iceland', cnName: '冰岛', countryCode: 'IS', telSortCode: 354 },
  { name: 'India', cnName: '印度', countryCode: 'IN', telSortCode: 91 },
  { name: 'Indonesia', cnName: '印度尼西亚', countryCode: 'ID', telSortCode: 62 },
  { name: 'Iran', cnName: '伊朗', countryCode: 'IR', telSortCode: 98 },
  { name: 'Iraq', cnName: '伊拉克', countryCode: 'IQ', telSortCode: 964 },
  { name: 'Ireland', cnName: '爱尔兰', countryCode: 'IE', telSortCode: 353 },
  { name: 'Isle of Man', cnName: '马恩岛', countryCode: 'IM', telSortCode: 44 },
  { name: 'Israel', cnName: '以色列', countryCode: 'IL', telSortCode: 972 },
  { name: 'Italy', cnName: '意大利', countryCode: 'IT', telSortCode: 39 },
  { name: 'Ivory Coast', cnName: '象牙海岸', countryCode: 'CI', telSortCode: 225 },
  { name: 'Jamaica', cnName: '牙买加', countryCode: 'JM', telSortCode: 1 },
  { name: 'Japan', cnName: '日本', countryCode: 'JP', telSortCode: 81 },
  { name: 'Jersey', cnName: '新泽西', countryCode: 'JE', telSortCode: 44 },
  { name: 'Jordan', cnName: '约旦', countryCode: 'JO', telSortCode: 962 },
  { name: 'Kazakhstan', cnName: '哈萨克斯坦', countryCode: 'KZ', telSortCode: 7 },
  { name: 'Kenya', cnName: '肯尼亚', countryCode: 'KE', telSortCode: 254 },
  { name: 'Kiribati', cnName: '基里巴斯', countryCode: 'KI', telSortCode: 686 },
  { name: 'Kosovo', cnName: '科索沃', countryCode: 'XK', telSortCode: 383 },
  { name: 'Kuwait', cnName: '科威特', countryCode: 'KW', telSortCode: 965 },
  { name: 'Kyrgyzstan', cnName: '吉尔吉斯斯坦', countryCode: 'KG', telSortCode: 996 },
  { name: 'Laos', cnName: '老挝', countryCode: 'LA', telSortCode: 856 },
  { name: 'Latvia', cnName: '拉脱维亚', countryCode: 'LV', telSortCode: 371 },
  { name: 'Lebanon', cnName: '黎巴嫩', countryCode: 'LB', telSortCode: 961 },
  { name: 'Lesotho', cnName: '莱索托', countryCode: 'LS', telSortCode: 266 },
  { name: 'Liberia', cnName: '利比里亚', countryCode: 'LR', telSortCode: 231 },
  { name: 'Libya', cnName: '利比亚', countryCode: 'LY', telSortCode: 218 },
  { name: 'Liechtenstein', cnName: '列支敦士登', countryCode: 'LI', telSortCode: 423 },
  { name: 'Lithuania', cnName: '立陶宛', countryCode: 'LT', telSortCode: 370 },
  { name: 'Luxembourg', cnName: '卢森堡', countryCode: 'LU', telSortCode: 352 },
  { name: 'Macao Special Administrative Region ', cnName: '澳门特别行政区', countryCode: 'MO', telSortCode: 853 },
  { name: 'Macedonia', cnName: '马其顿', countryCode: 'MK', telSortCode: 389 },
  { name: 'Madagascar', cnName: '马达加斯加', countryCode: 'MG', telSortCode: 261 },
  { name: 'Malawi', cnName: '马拉维', countryCode: 'MW', telSortCode: 265 },
  // { name: 'Malay Chinese Region', cnName: '马来华语区', countryCode: 'MYC', telSortCode: 60 },
  // { name: 'Malay Non-Chinese Region', cnName: '马来非华语区', countryCode: 'MYNC', telSortCode: 60 },
  { name: 'Malaysia', cnName: '马来西亚', countryCode: 'MY', telSortCode: 60 },
  { name: 'Maldives', cnName: '马尔代夫', countryCode: 'MV', telSortCode: 960 },
  { name: 'Mali', cnName: '马里', countryCode: 'ML', telSortCode: 223 },
  { name: 'Malta', cnName: '马耳他', countryCode: 'MT', telSortCode: 356 },
  { name: 'Marshall Islands', cnName: '马绍尔群岛', countryCode: 'MH', telSortCode: 692 },
  { name: 'Mauritania', cnName: '毛里塔尼亚', countryCode: 'MR', telSortCode: 222 },
  { name: 'Mauritius', cnName: '毛里求斯', countryCode: 'MU', telSortCode: 230 },
  { name: 'Mayotte', cnName: '马约特', countryCode: 'YT', telSortCode: 262 },
  { name: 'Mexico', cnName: '墨西哥', countryCode: 'MX', telSortCode: 52 },
  { name: 'Micronesia', cnName: '密克罗尼西亚', countryCode: 'FM', telSortCode: 691 },
  { name: 'Moldova', cnName: '摩尔多瓦', countryCode: 'MD', telSortCode: 373 },
  { name: 'Monaco', cnName: '摩纳哥', countryCode: 'MC', telSortCode: 377 },
  { name: 'Mongolia', cnName: '蒙古', countryCode: 'MN', telSortCode: 976 },
  { name: 'Montenegro', cnName: '黑山', countryCode: 'ME', telSortCode: 382 },
  { name: 'Montserrat', cnName: '蒙特塞拉特', countryCode: 'MS', telSortCode: 1 },
  { name: 'Morocco', cnName: '摩洛哥', countryCode: 'MA', telSortCode: 212 },
  { name: 'Mozambique', cnName: '莫桑比克', countryCode: 'MZ', telSortCode: 258 },
  { name: 'Myanmar', cnName: '缅甸', countryCode: 'MM', telSortCode: 95 },
  { name: 'Namibia', cnName: '纳米比亚', countryCode: 'NA', telSortCode: 264 },
  { name: 'Nauru', cnName: '瑙鲁', countryCode: 'NR', telSortCode: 674 },
  { name: 'Nepal', cnName: '尼泊尔', countryCode: 'NP', telSortCode: 977 },
  { name: 'Netherlands', cnName: '荷兰', countryCode: 'NL', telSortCode: 31 },
  { name: 'Netherlands Antilles', cnName: '荷属安的列斯', countryCode: 'AN', telSortCode: 599 },
  { name: 'New Caledonia', cnName: '新喀里多尼亚', countryCode: 'NC', telSortCode: 687 },
  { name: 'New Zealand', cnName: '新西兰', countryCode: 'NZ', telSortCode: 64 },
  { name: 'Nicaragua', cnName: '尼加拉瓜', countryCode: 'NI', telSortCode: 505 },
  { name: 'Niger', cnName: '尼日尔', countryCode: 'NE', telSortCode: 227 },
  { name: 'Nigeria', cnName: '尼日利亚', countryCode: 'NG', telSortCode: 234 },
  { name: 'Niue', cnName: '纽埃', countryCode: 'NU', telSortCode: 683 },
  { name: 'North Korea', cnName: '北朝鲜', countryCode: 'KP', telSortCode: 850 },
  { name: 'Northern Mariana Islands', cnName: '北马里亚纳群岛', countryCode: 'MP', telSortCode: 1 },
  { name: 'Norway', cnName: '挪威', countryCode: 'NO', telSortCode: 47 },
  { name: 'Oman', cnName: '阿曼', countryCode: 'OM', telSortCode: 968 },
  { name: 'Pakistan', cnName: '巴基斯坦', countryCode: 'PK', telSortCode: 92 },
  { name: 'Palau', cnName: '帕劳', countryCode: 'PW', telSortCode: 680 },
  { name: 'Palestine', cnName: '巴勒斯坦', countryCode: 'PS', telSortCode: 970 },
  { name: 'Panama', cnName: '巴拿马', countryCode: 'PA', telSortCode: 507 },
  { name: 'Papua New Guinea', cnName: '巴布亚新几内亚', countryCode: 'PG', telSortCode: 675 },
  { name: 'Paraguay', cnName: '巴拉圭', countryCode: 'PY', telSortCode: 595 },
  { name: 'Peru', cnName: '秘鲁', countryCode: 'PE', telSortCode: 51 },
  { name: 'Philippines', cnName: '菲律宾', countryCode: 'PH', telSortCode: 63 },
  { name: 'Pitcairn', cnName: '皮特凯恩', countryCode: 'PN', telSortCode: 64 },
  { name: 'Poland', cnName: '波兰', countryCode: 'PL', telSortCode: 48 },
  { name: 'Portugal', cnName: '葡萄牙', countryCode: 'PT', telSortCode: 351 },
  { name: 'Puerto Rico', cnName: '波多黎各', countryCode: 'PR', telSortCode: 1 },
  { name: 'Qatar', cnName: '卡塔尔', countryCode: 'QA', telSortCode: 974 },
  { name: 'Republic of the Congo', cnName: '刚果民主共和国', countryCode: 'CG', telSortCode: 242 },
  { name: 'Reunion', cnName: '团圆', countryCode: 'RE', telSortCode: 262 },
  { name: 'Romania', cnName: '罗马尼亚', countryCode: 'RO', telSortCode: 40 },
  { name: 'Russia', cnName: '俄国', countryCode: 'RU', telSortCode: 7 },
  { name: 'Rwanda', cnName: '卢旺达', countryCode: 'RW', telSortCode: 250 },
  { name: 'Saint Barthelemy', cnName: '圣巴泰勒米', countryCode: 'BL', telSortCode: 590 },
  { name: 'Saint Helena', cnName: '圣赫勒拿', countryCode: 'SH', telSortCode: 290 },
  { name: 'Saint Kitts and Nevis', cnName: '圣基茨和尼维斯', countryCode: 'KN', telSortCode: 1 },
  { name: 'Saint Lucia', cnName: '圣卢西亚', countryCode: 'LC', telSortCode: 1 },
  { name: 'Saint Martin', cnName: '圣马丁', countryCode: 'MF', telSortCode: 590 },
  { name: 'Saint Pierre and Miquelon', cnName: '圣皮埃尔和密克隆', countryCode: 'PM', telSortCode: 508 },
  { name: 'Saint Vincent and the Grenadines', cnName: '圣文森特和格林纳丁斯', countryCode: 'VC', telSortCode: 1 },
  { name: 'Samoa', cnName: '萨摩亚', countryCode: 'WS', telSortCode: 685 },
  { name: 'San Marino', cnName: '圣马力诺', countryCode: 'SM', telSortCode: 378 },
  { name: 'Sao Tome and Principe', cnName: '圣多美和普林西比', countryCode: 'ST', telSortCode: 239 },
  { name: 'Saudi Arabia', cnName: '沙特阿拉伯', countryCode: 'SA', telSortCode: 966 },
  { name: 'Senegal', cnName: '塞内加尔', countryCode: 'SN', telSortCode: 221 },
  { name: 'Serbia', cnName: '塞尔维亚', countryCode: 'RS', telSortCode: 381 },
  { name: 'Seychelles', cnName: '塞舌尔', countryCode: 'SC', telSortCode: 248 },
  { name: 'Sierra Leone', cnName: '塞拉利昂', countryCode: 'SL', telSortCode: 232 },
  { name: 'Singapore', cnName: '新加坡', countryCode: 'SG', telSortCode: 65 },
  { name: 'Sint Maarten', cnName: '圣马丁岛', countryCode: 'SX', telSortCode: 1 },
  { name: 'Slovakia', cnName: '斯洛伐克', countryCode: 'SK', telSortCode: 421 },
  { name: 'Slovenia', cnName: '斯洛文尼亚', countryCode: 'SI', telSortCode: 386 },
  { name: 'Solomon Islands', cnName: '所罗门群岛', countryCode: 'SB', telSortCode: 677 },
  { name: 'Somalia', cnName: '索马里', countryCode: 'SO', telSortCode: 252 },
  { name: 'South Africa', cnName: '南非', countryCode: 'ZA', telSortCode: 27 },
  { name: 'South Korea', cnName: '韩国', countryCode: 'KR', telSortCode: 82 },
  { name: 'South Sudan', cnName: '南苏丹', countryCode: 'SS', telSortCode: 211 },
  { name: 'Spain', cnName: '西班牙', countryCode: 'ES', telSortCode: 34 },
  { name: 'Sri Lanka', cnName: '斯里兰卡', countryCode: 'LK', telSortCode: 94 },
  { name: 'Sudan', cnName: '苏丹', countryCode: 'SD', telSortCode: 249 },
  { name: 'Suriname', cnName: '苏里南', countryCode: 'SR', telSortCode: 597 },
  { name: 'Svalbard and Jan Mayen', cnName: '斯瓦尔巴特', countryCode: 'SJ', telSortCode: 47 },
  { name: 'Swaziland', cnName: '斯威士兰', countryCode: 'SZ', telSortCode: 268 },
  { name: 'Sweden', cnName: '瑞典', countryCode: 'SE', telSortCode: 46 },
  { name: 'Switzerland', cnName: '瑞士', countryCode: 'CH', telSortCode: 41 },
  { name: 'Syria', cnName: '叙利亚', countryCode: 'SY', telSortCode: 963 },
  { name: 'Taiwan', cnName: '台湾', countryCode: 'TW', telSortCode: 886 },
  { name: 'Tajikistan', cnName: '塔吉克斯坦', countryCode: 'TJ', telSortCode: 992 },
  { name: 'Tanzania', cnName: '坦桑尼亚', countryCode: 'TZ', telSortCode: 255 },
  { name: 'Thailand', cnName: '泰国', countryCode: 'TH', telSortCode: 66 },
  { name: 'Togo', cnName: '多哥', countryCode: 'TG', telSortCode: 228 },
  { name: 'Tokelau', cnName: '托克劳', countryCode: 'TK', telSortCode: 690 },
  { name: 'Tonga', cnName: '汤加', countryCode: 'TO', telSortCode: 676 },
  { name: 'Trinidad and Tobago', cnName: '特立尼达和多巴哥', countryCode: 'TT', telSortCode: 1 },
  { name: 'Tunisia', cnName: '突尼斯', countryCode: 'TN', telSortCode: 216 },
  { name: 'Turkey', cnName: '土耳其', countryCode: 'TR', telSortCode: 90 },
  { name: 'Turkmenistan', cnName: '土库曼斯坦', countryCode: 'TM', telSortCode: 993 },
  { name: 'Turks and Caicos Islands', cnName: '特克斯和凯科斯群岛', countryCode: 'TC', telSortCode: 1 },
  { name: 'Tuvalu', cnName: '图瓦卢', countryCode: 'TV', telSortCode: 688 },
  { name: 'U.S. Virgin Islands', cnName: '美属维尔京群岛', countryCode: 'VI', telSortCode: 1 },
  { name: 'Uganda', cnName: '乌干达', countryCode: 'UG', telSortCode: 256 },
  { name: 'Ukraine', cnName: '乌克兰', countryCode: 'UA', telSortCode: 380 },
  { name: 'United Arab', cnName: '阿拉伯联合酋长国', countryCode: 'AE', telSortCode: 971 },
  { name: 'United Kingd', cnName: '英国', countryCode: 'GB', telSortCode: 44 },
  { name: 'United States', cnName: '美国', countryCode: 'US', telSortCode: 1 },
  { name: 'Uruguay', cnName: '乌拉圭', countryCode: 'UY', telSortCode: 598 },
  { name: 'Uzbekistan', cnName: '乌兹别克斯坦', countryCode: 'UZ', telSortCode: 998 },
  { name: 'Vanuatu', cnName: '瓦努阿图', countryCode: 'VU', telSortCode: 678 },
  { name: 'Vatican', cnName: '教廷', countryCode: 'VA', telSortCode: 379 },
  { name: 'Venezuela', cnName: '委内瑞拉', countryCode: 'VE', telSortCode: 58 },
  { name: 'Vietnam', cnName: '越南', countryCode: 'VN', telSortCode: 84 },
  { name: 'Wallis and Futuna', cnName: '瓦利斯和富图纳群岛', countryCode: 'WF', telSortCode: 681 },
  { name: 'Western Sahara', cnName: '西撒哈拉', countryCode: 'EH', telSortCode: 212 },
  { name: 'Yemen', cnName: '也门', countryCode: 'YE', telSortCode: 967 },
  { name: 'Zambia', cnName: '赞比亚', countryCode: 'ZM', telSortCode: 260 },
  { name: 'Zimbabwe', cnName: '津巴布韦', countryCode: 'ZW', telSortCode: 263 }
];
